# Generated by Django 2.0.5 on 2018-06-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prof_Data', '0002_auto_20180616_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='Prof_Course',
        ),
        migrations.AddField(
            model_name='prof',
            name='Course',
            field=models.CharField(default='NULL', max_length=200),
            preserve_default=False,
        ),
    ]
