# Generated by Django 2.0.5 on 2018-06-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Data', '0012_auto_20180616_2347'),
        ('Prof_Data', '0003_auto_20180616_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='Course',
        ),
        migrations.AddField(
            model_name='prof',
            name='Prof_Course',
            field=models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, to='Student_Data.Course'),
            preserve_default=False,
        ),
    ]
