# Generated by Django 2.0.5 on 2018-06-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prof_Data', '0004_auto_20180616_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='Prof_Id',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
