# Generated by Django 2.0.5 on 2018-06-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prof_Data', '0005_prof_prof_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='id',
        ),
        migrations.AlterField(
            model_name='prof',
            name='Prof_Id',
            field=models.CharField(default='0000', max_length=10, primary_key=True, serialize=False),
        ),
    ]
