# Generated by Django 2.0.5 on 2018-06-04 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=100)),
                ('Course_Code', models.CharField(max_length=10)),
                ('Credits', models.CharField(max_length=5)),
                ('No_of_Lectures', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='students',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Data.Student'),
        ),
    ]
