# Generated by Django 2.0.5 on 2018-06-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Data', '0002_auto_20180604_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
