# Generated by Django 2.0.5 on 2018-06-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Data', '0012_auto_20180616_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_Prof',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
